# 1. Import the dataset using Pandas from above mentioned url

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/SR1608/Datasets/main/covid-data.csv")
df

URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

# 2. High Level Data Understanding:

In [5]:
#a.Find no. of rows & columns in the dataset

print("Rows and Columns:", df.shape)

Rows and Columns: (57394, 49)

In [7]:
#b.Data types of columns.
print("Data Types of Column:", df.dtypes)

Data Types of Column: iso_code                               object
continent                              object
location                               object
date                                   object
total_cases                           float64
new_cases                             float64
new_cases_smoothed                    float64
total_deaths                          float64
new_deaths                            float64
new_deaths_smoothed                   float64
total_cases_per_million               float64
new_cases_per_million                 float64
new_cases_smoothed_per_million        float64
total_deaths_per_million              float64
new_deaths_per_million                float64
new_deaths_smoothed_per_million       float64
reproduction_rate                     float64
icu_patients                          float64
icu_patients_per_million              float64
hosp_patients                         float64
hosp_patients_per_million             float64
weekly_icu_admissions                 float64
weekly_icu_admissions_per_million     float64
weekly_hosp_admissions                float64
weekly_hosp_admissions_per_million    float64
total_tests                           float64
new_tests                             float64
total_tests_per_thousand              float64
new_tests_per_thousand                float64
new_tests_smoothed                    float64
new_tests_smoothed_per_thousand       float64
tests_per_case                        float64
positive_rate                         float64
stringency_index                      float64
population                            float64
population_density                    float64
median_age                            float64
aged_65_older                         float64
aged_70_older                         float64
gdp_per_capita                        float64
extreme_poverty                       float64
cardiovasc_death_rate                 float64
diabetes_prevalence                   float64
female_smokers                        float64
male_smokers                          float64
handwashing_facilities                float64
hospital_beds_per_thousand            float64
life_expectancy                       float64
human_development_index               float64
dtype: object

In [11]:
#C. Info & describe of data in dataframe
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57394 entries, 0 to 57393
Data columns (total 49 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   iso_code                            57071 non-null  object
 1   continent                           56748 non-null  object
 2   location                            57394 non-null  object
 3   date                                57394 non-null  object
 4   total_cases                         53758 non-null  float64
 5   new_cases                           56465 non-null  float64
 6   new_cases_smoothed                  55652 non-null  float64
 7   total_deaths                        44368 non-null  float64
 8   new_deaths                          56465 non-null  float64
 9   new_deaths_smoothed                 55652 non-null  float64
 10  total_cases_per_million             53471 non-null  float64
 11  new_cases_per_million               56401 non-null  float64
 12  new_cases_smoothed_per_million      55587 non-null  float64
 13  total_deaths_per_million            44096 non-null  float64
 14  new_deaths_per_million              56401 non-null  float64
 15  new_deaths_smoothed_per_million     55587 non-null  float64
 16  reproduction_rate                   37696 non-null  float64
 17  icu_patients                        4490 non-null   float64
 18  icu_patients_per_million            4490 non-null   float64
 19  hosp_patients                       5005 non-null   float64
 20  hosp_patients_per_million           5005 non-null   float64
 21  weekly_icu_admissions               357 non-null    float64
 22  weekly_icu_admissions_per_million   357 non-null    float64
 23  weekly_hosp_admissions              645 non-null    float64
 24  weekly_hosp_admissions_per_million  645 non-null    float64
 25  total_tests                         22017 non-null  float64
 26  new_tests                           21787 non-null  float64
 27  total_tests_per_thousand            22017 non-null  float64
 28  new_tests_per_thousand              21787 non-null  float64
 29  new_tests_smoothed                  24612 non-null  float64
 30  new_tests_smoothed_per_thousand     24612 non-null  float64
 31  tests_per_case                      22802 non-null  float64
 32  positive_rate                       23211 non-null  float64
 33  stringency_index                    47847 non-null  float64
 34  population                          57071 non-null  float64
 35  population_density                  54371 non-null  float64
 36  median_age                          51034 non-null  float64
 37  aged_65_older                       50265 non-null  float64
 38  aged_70_older                       50768 non-null  float64
 39  gdp_per_capita                      50367 non-null  float64
 40  extreme_poverty                     33571 non-null  float64
 41  cardiovasc_death_rate               51013 non-null  float64
 42  diabetes_prevalence                 52881 non-null  float64
 43  female_smokers                      39669 non-null  float64
 44  male_smokers                        39156 non-null  float64
 45  handwashing_facilities              24176 non-null  float64
 46  hospital_beds_per_thousand          45936 non-null  float64
 47  life_expectancy                     56336 non-null  float64
 48  human_development_index             49247 non-null  float64
dtypes: float64(45), object(4)
memory usage: 21.5+ MB
None
        total_cases      new_cases  new_cases_smoothed  total_deaths
count  5.375800e+04   56465.000000        55652.000000  4.436800e+04  \
mean   1.677974e+05    1953.576941         1920.431953  6.858639e+03
std    1.693038e+06   18269.650340        17777.391785  5.578081e+04
min    1.000000e+00   -8261.000000         -552.000000  1.000000e+00
25%    1.800000e+02       0.000000            0.857000  1.300000e+01
50%    2.070000e+03      14.000000           19.429000  8.400000e+01
75%    2.235675e+04     235.000000          245.286000  7.270000e+02
max    5.515465e+07  646281.000000       584981.857000  1.328537e+06

         new_deaths  new_deaths_smoothed  total_cases_per_million
count  56465.000000         55652.000000             53471.000000  \
mean      47.054317            46.835439              3139.099982
std      390.853776           378.272794              6183.455260
min    -1918.000000          -232.143000                 0.001000
25%        0.000000             0.000000                90.033000
50%        0.000000             0.286000               593.663000
75%        4.000000             4.000000              3487.050000
max    10600.000000          9027.714000             76541.772000

       new_cases_per_million  new_cases_smoothed_per_million
count           56401.000000                    55587.000000  \
mean               39.344804                       38.403211
std               133.985155                      101.649441
min             -2212.545000                     -269.978000
25%                 0.000000                        0.260000
50%                 2.194000                        3.863000
75%                25.941000                       29.678500
max              8652.658000                     2472.188000

       total_deaths_per_million  ...  gdp_per_capita  extreme_poverty
count              44096.000000  ...    50367.000000     33571.000000  \
mean                  95.335293  ...    20620.172071        12.435453
std                  180.721699  ...    20310.999832        19.427924
min                    0.000000  ...      661.240000         0.100000
25%                    3.977750  ...     5321.444000         0.500000
50%                   20.383000  ...    13913.839000         2.000000
75%                   90.571250  ...    31400.840000        18.100000
max                 1248.014000  ...   116935.600000        77.600000

       cardiovasc_death_rate  diabetes_prevalence  female_smokers
count           51013.000000         52881.000000    39669.000000  \
mean              252.646642             8.070269       10.741569
std               117.522344             4.189605       10.470743
min                79.370000             0.990000        0.100000
25%               156.139000             5.310000        1.900000
50%               238.339000             7.110000        6.400000
75%               318.991000            10.390000       19.600000
max               724.417000            30.530000       44.000000

       male_smokers  handwashing_facilities  hospital_beds_per_thousand
count  39156.000000            24176.000000                45936.000000  \
mean      32.642686               52.089636                    3.089724
std       13.453566               31.645306                    2.513193
min        7.700000                1.188000                    0.100000
25%       21.400000               21.222000                    1.300000
50%       31.400000               52.232000                    2.500000
75%       40.900000               83.741000                    4.200000
max       78.100000               98.999000                   13.800000

       life_expectancy  human_development_index
count     56336.000000             49247.000000
mean         73.937780                 0.722223
std           7.397016                 0.153261
min          53.280000                 0.354000
25%          69.870000                 0.601000
50%          75.345000                 0.752000
75%          79.380000                 0.847000
max          86.750000                 0.953000

[8 rows x 45 columns]

# 3. Low Level Data Understanding :

In [16]:
#a.Find count of unique values in location column.

df.location.unique().size

216

In [25]:
#b. Find which continent has maximum frequency using values counts.

df.continent.value_counts().idxmax()

'Europe'

In [27]:
# c. Find maximum & mean value in 'total_cases'.

print(df.total_cases.max())
print(df.total_cases.mean())

55154651.0
167797.3688753302

In [30]:
#d. Find 25%,50% & 75% quartile value in 'total_deaths'.

df.total_deaths.quantile([0.25, 0.50,0.75])

0.25     13.0
0.50     84.0
0.75    727.0
Name: total_deaths, dtype: float64

In [33]:
#e. Find which continent has maximum 'human_development_index'.

df.continent.loc[df.human_development_index.idxmax()]

'Europe'

In [35]:
#f. Find which continent has minimum 'gdp_per_capita'

df.continent.loc[df.gdp_per_capita.idxmin()]

'Africa'

# 4. Filter the dataframe with only this columns
['continent','location','date','total_cases','total_deaths','gdp_per_ca
pita','
human_development_index'] and update the data frame.

In [46]:
df = df[['continent','location','date','total_cases','total_deaths','gdp_per_capita','human_development_index']]
df

,continent,location,date,total_cases,total_deaths,gdp_per_capita,human_development_index
0,Asia,Afghanistan,31/12/19,NaN,NaN,1803.987,0.498
1,Asia,Afghanistan,01/01/20,NaN,NaN,1803.987,0.498
2,Asia,Afghanistan,02/01/20,NaN,NaN,1803.987,0.498
3,Asia,Afghanistan,03/01/20,NaN,NaN,1803.987,0.498
4,Asia,Afghanistan,04/01/20,NaN,NaN,1803.987,0.498
...,...,...,...,...,...,...,...
57389,NaN,International,13/11/20,696.0,7.0,NaN,NaN
57390,NaN,International,14/11/20,696.0,7.0,NaN,NaN
57391,NaN,International,15/11/20,696.0,7.0,NaN,NaN
57392,NaN,International,16/11/20,696.0,7.0,NaN,NaN
57393,NaN,International,17/11/20,696.0,7.0,NaN,NaN

# 5. Data Cleaning

In [47]:
#a. Remove all duplicates observations

df.drop_duplicates()

,continent,location,date,total_cases,total_deaths,gdp_per_capita,human_development_index
0,Asia,Afghanistan,31/12/19,NaN,NaN,1803.987,0.498
1,Asia,Afghanistan,01/01/20,NaN,NaN,1803.987,0.498
2,Asia,Afghanistan,02/01/20,NaN,NaN,1803.987,0.498
3,Asia,Afghanistan,03/01/20,NaN,NaN,1803.987,0.498
4,Asia,Afghanistan,04/01/20,NaN,NaN,1803.987,0.498
...,...,...,...,...,...,...,...
57389,NaN,International,13/11/20,696.0,7.0,NaN,NaN
57390,NaN,International,14/11/20,696.0,7.0,NaN,NaN
57391,NaN,International,15/11/20,696.0,7.0,NaN,NaN
57392,NaN,International,16/11/20,696.0,7.0,NaN,NaN
57393,NaN,International,17/11/20,696.0,7.0,NaN,NaN

In [49]:
#b.Find missing values in all columns

df.isna().sum()

continent                    646
location                       0
date                           0
total_cases                 3636
total_deaths               13026
gdp_per_capita              7027
human_development_index     8147
dtype: int64

In [51]:
# c. Remove all observations where continent column value is missing

df.dropna(subset=["continent"])

,continent,location,date,total_cases,total_deaths,gdp_per_capita,human_development_index
0,Asia,Afghanistan,31/12/19,NaN,NaN,1803.987,0.498
1,Asia,Afghanistan,01/01/20,NaN,NaN,1803.987,0.498
2,Asia,Afghanistan,02/01/20,NaN,NaN,1803.987,0.498
3,Asia,Afghanistan,03/01/20,NaN,NaN,1803.987,0.498
4,Asia,Afghanistan,04/01/20,NaN,NaN,1803.987,0.498
...,...,...,...,...,...,...,...
56743,Africa,Zimbabwe,13/11/20,8696.0,255.0,1899.775,0.535
56744,Africa,Zimbabwe,14/11/20,8765.0,257.0,1899.775,0.535
56745,Africa,Zimbabwe,15/11/20,8786.0,257.0,1899.775,0.535
56746,Africa,Zimbabwe,16/11/20,8786.0,257.0,1899.775,0.535
56747,Africa,Zimbabwe,17/11/20,8897.0,257.0,1899.775,0.535

In [52]:
#d. Fill all missing values with 0

df.fillna(0)

,continent,location,date,total_cases,total_deaths,gdp_per_capita,human_development_index
0,Asia,Afghanistan,31/12/19,0.0,0.0,1803.987,0.498
1,Asia,Afghanistan,01/01/20,0.0,0.0,1803.987,0.498
2,Asia,Afghanistan,02/01/20,0.0,0.0,1803.987,0.498
3,Asia,Afghanistan,03/01/20,0.0,0.0,1803.987,0.498
4,Asia,Afghanistan,04/01/20,0.0,0.0,1803.987,0.498
...,...,...,...,...,...,...,...
57389,0,International,13/11/20,696.0,7.0,0.000,0.000
57390,0,International,14/11/20,696.0,7.0,0.000,0.000
57391,0,International,15/11/20,696.0,7.0,0.000,0.000
57392,0,International,16/11/20,696.0,7.0,0.000,0.000
57393,0,International,17/11/20,696.0,7.0,0.000,0.000

# 6. Data Time Format

In [3]:
df[date] = pd.to_datetime(df['date'])
df

NameError: name 'df' is not defined

In [6]:
# Create new column after exteacting month data from date

df['month'] = df['date'].dt.month

df.head()

NameError: name 'df' is not defined

# 7. Data Aggregation

In [7]:
df_groupby = df.groupby('continent').max.reset_index()
df_groupby

NameError: name 'df' is not defined

# 8.Feature Engineering

In [ ]:
df1 = df_groupby['total_deaths']/df_groupby['total_cases']

df1

# Data Visusalization

In [ ]:
sns.distplot(df_groupby['gdp_per_capita'],kde=False)

In [ ]:
#Plot a scatterplot of 'total_cases' & 'gdp_per_capita'

sns.scatterplot(df_groupby['total_cases'],df_groupby['gdp_per_capita'])

In [ ]:
#Plot pairplot on df_groupby by dataset

sns.pairplot(df_groupby)

In [ ]:
#Plot a barplot of 'continent' column with 'total_cases'



sns.catplot(x='continent',y='total_cases',data=df_groupby,kind='bar')

In [ ]:


df_groupby.to_csv('df_groupby.csv',index=False)